### ISSUE TITLE
Make alt text more informative

### ISSUE THREAD

**Issue by jooyoungseo** [jooyoungseo/assets2023_vscode#27]
It would be even nicer if we could make the alt text of our figures more informative and understandable. For example, "A screenshot of terminal buffer showing xxx."

**Comment by meganrogge** [comment]
Apologies if that isn't already the case - I had thought I added that. I'll investigate

**Comment by jooyoungseo** [comment]
No need to apologize. It’s there, but we may want to follow more conventional alt text description rules suggested by ACM: https://authors.acm.org/proceedings/production-information/describing-figures#:~:text=Focus%20the%20description%20on%20the,terminology%20as%20the%20main%20text.#h-how-do-i-write-a-good-figure-description?

1. Keep the description as short as possible, information over 2000 characters long (including spaces) will not be captured in a pdf.

2. Use unformatted plain text. That means no lists and no LaTeX markup.

3. Consider both the content and the function of the figure. Focus the description on the essential new information in the figure, beyond what is in the
text.

4. Make the first sentence (or the short description, if available) a ‘title’ less than 125 characters long.

5. Go from general to more specific details.

6. Use the same writing style and terminology as the main text.

7. Don’t repeat information that is already in the text.

8. The figure caption should not be part of the image, and the caption text should not be repeated. However, if the caption is part of the image, start
the description with the caption.

9. Write out abbreviations and symbols in full

10. Only mention color if the specific colors are important or used in the text.
